development: &development
    mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
    user_name: <%= ENV['USER_NAME'] %>
    password: <%= ENV['PASSWORD'] %>
    address: <%= ENV['ADDRESS'] %>
    domain: <%= ENV['DOMAIN'] %>
    portmail: <%= ENV['PORTMAIL'] %>

test:
    mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
    user_name: <%= ENV['USER_NAME'] %>
    password: <%= ENV['PASSWORD'] %>
    address: <%= ENV['ADDRESS'] %>
    domain: <%= ENV['DOMAIN'] %>
    portmail: <%= ENV['PORTMAIL'] %>

production:
    mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
    user_name: <%= ENV['USER_NAME'] %>
    password: <%= ENV['PASSWORD'] %>
    address: <%= ENV['ADDRESS'] %>
    domain: <%= ENV['DOMAIN'] %>
    portmail: <%= ENV['PORTMAIL'] %>