development: &development
    mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
    user_name: <%= ENV['USER_NAME'] %>
    password: <%= ENV['PASSWORD'] %>
    address: <%= ENV['ADDRESS'] %>
    domain: <%= ENV['DOMAIN'] %>
    portmail: <%= ENV['PORTMAIL'] %>
    cram_md5: <%= ENV['CRAM_MD5'] %>
    smtp: <%= ENV['SMTP'] %>

test: &test
   <<: *development

production: &production
   <<: *test